language: perl
sudo: false
matrix:
  include:
    - perl: "5.14.0"
    - perl: "5.26"
      env: RELEASE_TESTING=1
    # separate from release testing else cover_db blows up xt/manifest.t
    - perl: "5.26"
      env: COVERAGE=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0 # else makes build get deps wrong
  - source ~/travis-perl-helpers/init
  - env|sort
  - build-perl
  - local-lib cache
  - perl -V
  - cpan-install ExtUtils::MakeMaker~6.64 # for TEST_REQUIRES
  - if [ "$RELEASE_TESTING" = 1 ]; then cpan-install --deps; prove -l xt; fi
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
  # this is a workaround for https://github.com/pjcj/Devel--Cover/issues/164
  - export HARNESS_PERL_SWITCHES="-M\"5; BEGIN{ require B::Deparse; *B::Deparse::const = sub { goto &B::Deparse::const_dumper; } }\" $HARNESS_PERL_SWITCHES"
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
after_success:
  - coverage-report
notifications:
  irc:
    channels:
    - "irc.perl.org#graphql-perl"
    on_failure: always
    skip_join: true
